### ISSUE TITLE
all directpvs are Unavailable

### ISSUE THREAD

**Issue by pjy324** [minio/directpv#563] opened 2022-03-27 04:44 UTC
There is a problem with all drivers being Unavailable.
When you uninstall/install directpv with all disks mounted, the entire drive status appears as Unavailable.

So I added some disks on the pwk15 node. Then, I uninstalled/installed directpv.
Only one disk is in the Available state. Or it's all in the "Unavailable" state.

Can you tell me what the problem is?

There's another problem.

=========================================
1. kubectl directpv drives list -a

 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE              ACCESS-TIER  STATUS
....
 /dev/sda   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sda1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdb   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdb1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdc   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdc1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdd   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdd1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sde   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sde1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdf   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdf1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdg   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdg1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdh   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdh1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdi   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdi1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdj   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdj1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdk   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdk1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdl   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdl1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdm   1.7 TiB   -          -           -        pwk15  -            Unavailable
 /dev/sdm1  1.7 TiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdn   224 GiB   -          -           -        pwk15  -            Unavailable
 /dev/sdn1  512 MiB   -          xfs         -        pwk15  -            Unavailable
 /dev/sdn2  223 GiB   -          xfs         -        pwk15  -            Unavailable
...............

===============================================
2. mount | grep /dev (mount information for pwk15 nodes)
 
devtmpfs on /dev type devtmpfs (rw,nosuid,size=263774808k,nr_inodes=65943702,mode=755)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
/dev/sdn2 on / type xfs (rw,relatime,attr2,inode64,noquota)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
/dev/sdn1 on /boot type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdk1 on /data01 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdi1 on /data02 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdl1 on /data03 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdb1 on /data04 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdj1 on /data06 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sde1 on /data07 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdh1 on /data08 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdc1 on /data09 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdn2 on /var/lib/kubelet/pods/8bdaf116-a436-42c4-8901-e9fe79dc1d4e/volume-subpaths/config/wait-for-airflow-migrations/0 type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdn2 on /var/lib/kubelet/pods/8bdaf116-a436-42c4-8901-e9fe79dc1d4e/volume-subpaths/config/webserver/0 type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdn2 on /var/lib/kubelet/pods/8bdaf116-a436-42c4-8901-e9fe79dc1d4e/volume-subpaths/config/webserver/1 type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdn2 on /var/lib/kubelet/pods/8bdaf116-a436-42c4-8901-e9fe79dc1d4e/volume-subpaths/config/webserver/2 type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdd1 on /data05 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdm1 on /data11 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdf1 on /data12 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sda1 on /data10 type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sdg1 on /data13 type xfs (rw,noatime,attr2,inode64,noquota)

===========================================
3. I umounted 5 disks.

- umount /dev/sdd1
- umount /dev/sda1
- umount /dev/sdf1
- umount /dev/sdg1
- umount /dev/sdm1

[/var/log/messages log]
Mar 27 13:26:50 icsdchadooppwk15 kernel: XFS (loop0): Attempted to mount read-only compatible filesystem read-write.
Mar 27 13:26:50 icsdchadooppwk15 kernel: XFS (loop0): Filesystem can only be safely mounted read only.
Mar 27 13:26:50 icsdchadooppwk15 kernel: XFS (loop0): Ending clean mount
Mar 27 13:26:50 icsdchadooppwk15 kernel: XFS (loop0): Unmounting Filesystem
Mar 27 13:26:50 icsdchadooppwk15 kernel: XFS (sdd1): Ending clean mount
Mar 27 13:30:07 icsdchadooppwk15 kernel: XFS (sdd1): Unmounting Filesystem
Mar 27 13:30:10 icsdchadooppwk15 kernel: XFS (sda1): Unmounting Filesystem
Mar 27 13:30:12 icsdchadooppwk15 kernel: XFS (sdf1): Unmounting Filesystem
Mar 27 13:30:15 icsdchadooppwk15 kernel: XFS (sdg1): Unmounting Filesystem
Mar 27 13:30:17 icsdchadooppwk15 kernel: XFS (sdm1): Unmounting Filesystem

===============================================
4. directpv uninstall/install

kubectl directpv drives ls

 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE              ACCESS-TIER  STATUS
 /dev/sdd1  1.7 TiB   -          xfs         -        icsdchadooppwk15  -            Available

===============================================

**Comment by harshavardhana** [comment] 2022-03-27 04:44
Closing as duplicate of #562

**Closed by harshavardhana** 2022-03-27 04:44 UTC
